### ISSUE TITLE
Multiple Instances of jPush Menu

### ISSUE THREAD

**Issue by hunzaboy** [takien/jPushMenu#24]
Hi, 

Is there any way i can have multiple instances. 

I have 2 menus. And i want one to close on body click and the second should not close on body click. 

Any help will be appreciated.

**Comment by drawcard** [comment]
The demo page at http://takien.github.io/jPushMenu/ shows 6 instances of the menu working on a single page. It should be a matter of just assigning different button classes to each instance in Jquery. Inspect the source code of that page to see how it's done.

As for getting one to stay open while the other closes, that might be a bit trickier, but you could probably do it by setting one of the menus to close on body click, and set the other menu to not close on body click, ignoring the click altogether (using `closeOnClickOutside` parameter, which isn't documented as far as I know but perhaps the author can step in and explain better than I can! :+1: )

EDIT: Here's an example I've found: https://github.com/takien/jPushMenu/issues/1#issuecomment-18095890

**Comment by hunzaboy** [comment]
Thanks!
