### ISSUE TITLE
Hide the menu after a link is clicked

### ISSUE THREAD

**Issue by dandrews** [takien/jPushMenu#4]
Thanks for writing this plugin. Is there a simple way or extension to hide the menu after a link in the menu is clicked?

**Comment by dandrews** [comment]
I added an option <code>closeOnClickInside: true</code> and the following snippet:

```
if(o.closeOnClickInside) {
  $('.cbp-spmenu a').click(function(e){
    jPushMenu.close();
  });
}
```

**Comment by takien** [comment]
nice.

**Comment by takien** [comment]
Please fork and push so I can merge it. thanks.

**Comment by pascalf22** [comment]
Hello,
Thanks for this comment.... where do i should place this code : closeOnClickInside: true

thanks a lot !

**Comment by pascalf22** [comment]
Hello,

I need that the menu doesn't close on a clicl on it... so i try this.. 

jQuery(document).ready(function($) {
      $('.toggle-menu').jPushMenu({closeOnClickInside: false});

});

But it close when i cick...
I need it because i have a textbox in the menu to search... and when i click in the textbox.. the menu close...

thanks

**Comment by mimomedia** [comment]
Same issue here, any idea?

Thank you & Regards
